Repository FEUP-ESOF-2020-21/open-cx-t4g2-codemasters, pull requests merged in 2020-12, with the labels that each got.

#102 All comments are now displayed!
  src/lib/database/databaseService.dart
  src/lib/screens/post.dart
  src/lib/screens/rate_talk.dart
  src/lib/screens/see_comments.dart
  src/lib/widgets/feed/feed_carousel.dart
Labels: back-end, iteration-3

#104 Speaker popup
  src/lib/auth/Authentication.dart
  src/lib/model/conferenceModel.dart
  src/lib/model/speaker.dart
  src/lib/screens/create_conference.dart
  src/lib/screens/utils/button.dart
  src/lib/screens/utils/counter.dart
  src/lib/services/cloud_storage_result.dart
  src/pubspec.lock
Labels: back-end, bug, database, iteration-3, refactor

#106 Profile image
  src/assets/images/perfil.jpg
  src/lib/model/userModel.dart
  src/lib/screens/create_conference.dart
  src/lib/screens/edit_profile.dart
  src/lib/screens/profile.dart
  src/lib/widgets/profile/profile_photo.dart
Labels: back-end, conference manager, front-end, medium priority, profile manager

#107 Add comment date
  src/lib/model/conferenceModel.dart
  src/lib/screens/edit_profile.dart
  src/lib/screens/rate_talk.dart
  src/lib/screens/see_comments.dart
  src/lib/screens/signup.dart
Labels: front-end

#108 See all talks
  src/lib/screens/see_all_talks.dart
  src/lib/widgets/common/feed_common.dart
  src/lib/widgets/feed/feed_carousel.dart
Labels: back-end, front-end

#112 Back-end of explore done
  src/lib/screens/explore.dart
Labels: back-end, front-end, iteration-3, search

#120 Bug Solving
  src/lib/auth/userSetup.dart
Labels: bug

#126 Create Post error seems solved
  src/lib/screens/create_conference.dart
Labels: bug

#131 Update read me
  README.md
  docs/actually_leave_comment_mockup.png
  docs/actually_leave_rating_mockup.png
  docs/all_talks_mockup.png
  docs/comments_mockup.png
  docs/create_conference_mockup.png
  docs/edit_profile_mockup.png
  docs/explore_mockup.png
  docs/feed_mockup.png
  docs/leave_comment_mockup.png
  docs/leave_rating_mockup.png
  docs/login_mockup.png
  docs/post_mockup.png
  docs/profile_mockup.png
  docs/see_all_mockup.png
  docs/see_comments_mockup.png
  docs/sign_up_mockup.png
Labels: documentation, iteration-3

#132 Added user creator in firebase to a conference.
  src/lib/model/conferenceModel.dart
Labels: back-end, database, iteration-4

#133 Recommended conferences!
  src/lib/database/databaseService.dart
  src/lib/screens/create_conference.dart
  src/lib/screens/feed.dart
  src/lib/screens/see_all_talks.dart
  src/lib/screens/see_comments.dart
  src/lib/widgets/common/feed_common.dart
  src/lib/widgets/feed/feed_carousel.dart
Labels: back-end, front-end, iteration-4

#135 Conferences with tags that have rate less than 3 are not quoted as us…
  src/lib/database/databaseService.dart
Labels: back-end, iteration-4

#136 Create conference bugfixes
  src/lib/model/conferenceModel.dart
  src/lib/screens/create_conference.dart
  src/lib/screens/utils/counter.dart
Labels: back-end, front-end, iteration-3

#137 See talks added by user
  src/lib/model/conferenceModel.dart
  src/lib/screens/create_conference.dart
  src/lib/screens/profile.dart
  src/lib/screens/talks_added_by_user.dart
Labels: back-end, front-end, iteration-4

#140 Number of Posts and Rates given by the user.
  src/lib/auth/userSetup.dart
  src/lib/database/databaseService.dart
  src/lib/model/conferenceModel.dart
  src/lib/model/userModel.dart
  src/lib/screens/profile.dart
Labels: back-end, iteration-4

#141 Number of rating only evaluated on new ratings given.
  src/lib/database/databaseService.dart
Labels: back-end, iteration-4

#147 Merge feed explore
  src/assets/icons/1x/app-logo.png
  src/lib/main.dart
  src/lib/screens/explore.dart
  src/lib/screens/login.dart
  src/lib/screens/see_all_talks.dart
  src/lib/ui_elements.dart
  src/lib/widgets/feed/feed_carousel.dart
Labels: back-end, front-end, iteration-4

#156 Tag popup
  src/lib/model/conferenceModel.dart
  src/lib/screens/create_conference.dart
  src/lib/screens/utils/button.dart
  src/lib/screens/utils/errorMessage.dart
Labels: back-end, front-end, high priority, iteration-4

#158 Edit post
  src/lib/database/databaseService.dart
  src/lib/model/conference.dart
  src/lib/model/conferenceModel.dart
  src/lib/screens/create_conference.dart
  src/lib/screens/post.dart
  src/lib/screens/utils/counter.dart
  src/lib/screens/utils/field.dart
  src/lib/ui_elements.dart
  src/lib/widgets/profile/profile_photo.dart
Labels: back-end, front-end, high priority, iteration-4

#161 Corrected bug regarding rating of a talk.
  src/lib/screens/rate_talk.dart
Labels: bug

#162 Unit Testing
  src/lib/screens/feed.dart
  src/pubspec.lock
  src/pubspec.yaml
  src/test/login_test.dart
  src/test/recommended_test.dart
Labels: testing

#164 Fix bug edit-rate
  src/lib/model/conference.dart
  src/lib/screens/create_conference.dart
  src/lib/screens/post.dart
  src/lib/widgets/common/feed_common.dart
Labels: back-end, bug

#165 Flutter Gherkin tests done!
  src/lib/main.dart
  src/lib/screens/add_comment.dart
  src/lib/screens/edit_profile.dart
  src/lib/screens/explore.dart
  src/lib/screens/feed.dart
  src/lib/screens/login.dart
  src/lib/screens/post.dart
  src/lib/screens/rate_talk.dart
  src/lib/screens/utils/LabelSI.dart
  src/lib/screens/utils/field.dart
  src/lib/ui_elements.dart
  src/lib/widgets/profile/bio.dart
  src/lib/widgets/profile/edit_profile.dart
  src/lib/widgets/profile/name.dart
  src/pubspec.lock
  src/pubspec.yaml
  src/test_driver/app.dart
  src/test_driver/app_test.dart
  src/test_driver/features/profile.feature
  src/test_driver/steps/test_steps.dart
Labels: testing

#167 Recommended conferences fixed.
  src/lib/model/conferenceModel.dart
Labels: back-end, bug, front-end

#168 Update README
  README.md
  docs/button_toSee_MyPosts_mockup.png
  docs/create_conference_mockup.png
  docs/domain_model.png
  docs/edit_post.PNG
  docs/edit_post2.PNG
  docs/edit_profile_mockup.png
  docs/feed_mockup.png
  docs/myPosts_mockup.png
  docs/physical_architecture.png
  docs/post_mockup.png
  docs/profile_mockup.png
  docs/search.PNG
  docs/searchBar.PNG
  src/test/widget_test.dart
  src/test_driver/steps/test_steps.dart
Labels: documentation, iteration-4
