Repository FEUP-ESOF-2020-21/open-cx-t4g2-codemasters, pull requests merged in 2020-11, with the labels that each got.

#21 feed UI front-end
  src/assets/images/conference_test.jpg
  src/lib/main.dart
  src/lib/screens/feed.dart
  src/lib/style.dart
  src/lib/ui_elements.dart
  src/lib/widgets/feed/coming_next_carousel.dart
  src/lib/widgets/feed/feed_carousel.dart
  src/lib/widgets/feed/recommended_carousel.dart
  src/lib/widgets/feed/top_rated_carousel.dart
  src/pubspec.yaml
Labels: front-end

#23 signup front-end
  src/lib/main.dart
  src/lib/screens/signup.dart
  src/lib/screens/utils/label.dart
Labels: front-end

#30 Firebase
  src/android/app/build.gradle
  src/android/app/google-services.json
  src/android/build.gradle
  src/android/settings.gradle
  src/lib/auth/Authentication.dart
  src/lib/auth/userSetup.dart
  src/lib/auth/validation.dart
  src/lib/main.dart
  src/lib/model/userModel.dart
  src/lib/screens/login.dart
  src/lib/screens/signup.dart
  src/lib/screens/utils/field.dart
  src/lib/style.dart
  src/pubspec.lock
  src/pubspec.yaml
Labels: back-end, database, login

#32 Back-End Development - Feed
  src/lib/screens/feed.dart
  src/lib/widgets/feed/feed_carousel.dart
Labels: back-end

#51 Update README.md
  README.md
Labels: documentation, iteration-1

#52 Bottom navigation bar
  src/lib/main.dart
  src/lib/screens/feed.dart
  src/lib/screens/login.dart
  src/lib/screens/post.dart
  src/lib/ui_elements.dart
Labels: back-end, iteration-2, medium priority

#53 Connected feed to PostScreen. Still need to work with Speakers.
  src/lib/model/conference.dart
  src/lib/model/speaker.dart
  src/lib/screens/post.dart
  src/lib/widgets/feed/feed_carousel.dart
Labels: back-end, front-end

#62 Connected Back-End of User Profile.
  src/lib/database/databaseService.dart
  src/lib/model/userModel.dart
  src/lib/screens/feed.dart
  src/lib/screens/profile.dart
Labels: back-end, iteration-2

#68 Create conference Backend
  src/lib/model/conferenceModel.dart
  src/lib/screens/create_conference.dart
  src/lib/screens/signup.dart
Labels: back-end

#76 Back-End of edit Profile done.
  src/lib/auth/Authentication.dart
  src/lib/database/databaseService.dart
  src/lib/screens/edit_profile.dart
Labels: back-end, iteration-2

#77 Corrected small issue regarding user reauthentication.
  src/lib/auth/Authentication.dart
  src/lib/screens/edit_profile.dart
Labels: back-end, iteration-2

#82 Backend create conference handles speakers
  src/lib/model/conferenceModel.dart
  src/lib/model/speaker.dart
  src/lib/screens/create_conference.dart
Labels: back-end, database, iteration-3

#86 Update README
  README.md
Labels: documentation, iteration-2

#88 Fixed title alignment in post screen
  src/lib/screens/post.dart
Labels: bug, front-end, iteration-3

#89 Fixed field alignment in create conference screen
  src/lib/screens/create_conference.dart
Labels: bug, front-end, iteration-3

#92 Upload and visualize conferences images
  src/lib/model/conferenceModel.dart
  src/lib/screens/create_conference.dart
  src/lib/screens/post.dart
  src/lib/services/cloud_storage_result.dart
  src/lib/services/cloud_storage_service.dart
  src/lib/widgets/feed/feed_carousel.dart
  src/pubspec.lock
  src/pubspec.yaml
Labels: back-end, iteration-3

#96 Feature/rating backend
  src/lib/database/databaseService.dart
  src/lib/model/conference.dart
  src/lib/model/userModel.dart
  src/lib/screens/post.dart
  src/lib/screens/rate_talk.dart
Labels: back-end, iteration-3

#97 User can insert a comment about a specific Talk.
  src/lib/database/databaseService.dart
  src/lib/screens/add_comment.dart
  src/lib/screens/post.dart
  src/lib/screens/rate_talk.dart
Labels: back-end, iteration-3
